apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  namespace: octohelm
  name: k8s-proxy
rules:
  - verbs:
      - '*'
    apiGroups:
      - '*'
    resources:
      - '*'
  - verbs:
      - '*'
    nonResourceURLs:
      - '*'