kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: octohelm
  name: k8s-proxy
subjects:
- kind: ServiceAccount
  name: k8s-proxy
  namespace: octohelm
roleRef:
  kind: ClusterRole
  name: k8s-proxy
  apiGroup: rbac.authorization.k8s.io
